# Generated by Django 5.1.4 on 2026-02-23 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navmenuitem',
            options={'ordering': ['menu_type', 'order', 'label'], 'verbose_name': 'Navigation Menu Item', 'verbose_name_plural': 'Navigation Menu Items'},
        ),
        migrations.RemoveField(
            model_name='navmenuitem',
            name='title',
        ),
        migrations.AddField(
            model_name='navmenuitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='navmenuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fas fa-home)', max_length=100),
        ),
        migrations.AddField(
            model_name='navmenuitem',
            name='label',
            field=models.CharField(default='Menu Item', help_text='Display text for the menu item', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navmenuitem',
            name='target',
            field=models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=20),
        ),
        migrations.AddField(
            model_name='navmenuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='navmenuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on website'),
        ),
        migrations.AlterField(
            model_name='navmenuitem',
            name='menu_type',
            field=models.CharField(choices=[('main', 'Main Menu'), ('footer', 'Footer Links'), ('utility', 'Utility Links')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='navmenuitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (ascending)'),
        ),
        migrations.AlterField(
            model_name='navmenuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent menu item for submenu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contact.navmenuitem'),
        ),
        migrations.AlterField(
            model_name='navmenuitem',
            name='url',
            field=models.CharField(blank=True, help_text='URL or route name (e.g., /services/ or home)', max_length=200, null=True),
        ),
    ]
